### PR TITLE
[fix] join returns zero records

### PR DESCRIPTION
**Pull request by jaymehtasa**
Was throwing an error when returns zero records using join.

image

### CODE REVIEW

**Comment by jaymehtasa** [comment]
Please accept asap possible and release the patch, really appreciate it.

**Comment by ujjwalguptaofficial** [comment]
Please dont commit distributed files & dont change any version in package.json , only commit codes. It makes little harder for me to see what has code changes. And committing those files are irrelevant as i need to recreate them with newer changes . So keep your commit cleans with only codes. 

For more info, read contributing guidelines - https://github.com/ujjwalguptaofficial/JsStore/blob/master/CONTRIBUTING.MD

Thanks for your contribution. Keep doing it :).

**Comment by jaymehtasa** [comment]
Sure @ujjwalguptaofficial, can understand. will keep that in mind. Problem is our team uses forked version until PR gets merged, so for them, it's mandatory push build in master.

But I will find some middle way.

**Comment by jaymehtasa** [comment]
image

One more thing, I tried to look for Contribution guideline, which I found in your README.md file, but that link is broken, so please consider fixing it 😄

**Comment by ujjwalguptaofficial** [comment]
aha i see, will fix . Thanks.

**Comment by jaymehtasa** [comment]
@ujjwalguptaofficial 
Is there any slack channel available for JsStore, where we can discuss features/bugs?

**Comment by ujjwalguptaofficial** [comment]
Yes we use gitter for communication - https://gitter.im/JsStore/Lobby?source=orgpage. But i m planing to move to slack cause everyone now a days on slack. But for now , let's talk on gitter.

**Comment by ujjwalguptaofficial** [comment]
New version - 3.1.0 is released with your fix.

**Pull request merged**
